"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Sujani Srinivasan and Meghna Prabhakaran, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: sps2996
UT EID 2: mp52744
"""


# TODO: implement this function. You may delete this comment after you are done.
def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    fence = [['' for _ in range(len(string))] for _ in range(key)]
    row, step = 0, 1

    for i, char in enumerate(string):
        fence[row][i] = char
        if row == 0:
            step = 1
        elif row == key - 1:
            step = -1
        row += step

    result = ''.join([''.join(r) for r in fence])
    return result 


# TODO: implement this function. You may delete this comment after you are done.
def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    fence = [['' for _ in range(len(string))] for _ in range(key)]
    row, step = 0, 1
    for i in range(len(string)):
        fence[row][i] = '*'
        if row == 0:
            step = 1
        elif row == key - 1:
            step = -1
        row += step

    idx = 0
    for r in range(key):
        for c in range(len(string)):
            if fence[r][c] == '*' and idx < len(string):
                fence[r][c] = string[idx]
                idx += 1

    result = []
    row, step = 0, 1
    for i in range(len(string)):
        result.append(fence[row][i])
        if row == 0:
            step = 1
        elif row == key - 1:
            step = -1
        row += step

    return ''.join(result)
        


# TODO: implement this function. You may delete this comment after you are done.
def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    return ''.join([c for c in string.lower() if c.isalpha()])


# TODO: implement this function. You may delete this comment after you are done.
def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    return chr((ord(p) + ord(s) - 2 * ord('a')) % 26 + ord('a'))


# TODO: implement this function. You may delete this comment after you are done.
def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    return chr((ord(s) - ord(p) + 26) % 26 +ord('a'))


# TODO: implement this function. You may delete this comment after you are done.
def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    filtered = filter_string(string)
    encoded = ''
    for i, c in enumerate(filtered):
        encoded += encode_character(phrase[i % len(phrase)], c)
    return encoded


# TODO: implement this function. You may delete this comment after you are done.
def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    decoded = ''
    for i, c in enumerate(string):
        decoded += decode_character(phrase[i % len(phrase)], c)
    return decoded


# TODO: implement this function. You may delete this comment after you are done.
def main():
    """Main function that reads stdin and runs each cipher"""
    # Rail Fence Encode
    plain1 = input()
    key1 = int(input())
    encoded1 = rail_fence_encode(plain1, key1)

    print("Rail Fence Cipher\n")
    print(f"Plain Text: {plain1}")
    print(f"Key: {key1}")
    print(f"Encoded Text: {encoded1}\n")

    # Rail Fence Decode
    encoded2 = input()
    key2 = int(input())
    decoded2 = rail_fence_decode(encoded2, key2)

    print(f"Encoded Text: {encoded2}")
    print(f"Enter Key: {key2}")
    print(f"Decoded Text: {decoded2}")

    # Vigenere Encode
    plain3 = input()
    phrase1 = input()
    encoded3 = vigenere_encode(plain3, phrase1)

    print("Vigenere Cipher\n")
    print(f"Plain Text: {plain3}")
    print(f"Pass Phrase: {phrase1}")
    print(f"Encoded Text: {encoded3}\n")

    # Vigenere Decode
    encoded4 = input()
    phrase2 = input()
    decoded4 = vigenere_decode(encoded4, phrase2)

    print(f"Encoded Text: {encoded4}")
    print(f"Pass Phrase: {phrase2}")
    print(f"Decoded Text: {decoded4}")


# Do NOT modify the following code.
if __name__ == "__main__":
    main()
